# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InterfaceapiInitDataResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp': 'int',
        'markets': 'object',
        'commands_information': 'object'
    }

    attribute_map = {
        'timestamp': 'Timestamp',
        'markets': 'Markets',
        'commands_information': 'CommandsInformation'
    }

    def __init__(self, timestamp=None, markets=None, commands_information=None):  # noqa: E501
        """InterfaceapiInitDataResponse - a model defined in Swagger"""  # noqa: E501
        self._timestamp = None
        self._markets = None
        self._commands_information = None
        self.discriminator = None
        if timestamp is not None:
            self.timestamp = timestamp
        if markets is not None:
            self.markets = markets
        if commands_information is not None:
            self.commands_information = commands_information

    @property
    def timestamp(self):
        """Gets the timestamp of this InterfaceapiInitDataResponse.  # noqa: E501


        :return: The timestamp of this InterfaceapiInitDataResponse.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this InterfaceapiInitDataResponse.


        :param timestamp: The timestamp of this InterfaceapiInitDataResponse.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def markets(self):
        """Gets the markets of this InterfaceapiInitDataResponse.  # noqa: E501


        :return: The markets of this InterfaceapiInitDataResponse.  # noqa: E501
        :rtype: object
        """
        return self._markets

    @markets.setter
    def markets(self, markets):
        """Sets the markets of this InterfaceapiInitDataResponse.


        :param markets: The markets of this InterfaceapiInitDataResponse.  # noqa: E501
        :type: object
        """

        self._markets = markets

    @property
    def commands_information(self):
        """Gets the commands_information of this InterfaceapiInitDataResponse.  # noqa: E501


        :return: The commands_information of this InterfaceapiInitDataResponse.  # noqa: E501
        :rtype: object
        """
        return self._commands_information

    @commands_information.setter
    def commands_information(self, commands_information):
        """Sets the commands_information of this InterfaceapiInitDataResponse.


        :param commands_information: The commands_information of this InterfaceapiInitDataResponse.  # noqa: E501
        :type: object
        """

        self._commands_information = commands_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterfaceapiInitDataResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterfaceapiInitDataResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
