# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserapiRefreshSupportkeyResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'support_key': 'str',
        'valid_untill': 'int'
    }

    attribute_map = {
        'user_id': 'UserId',
        'support_key': 'SupportKey',
        'valid_untill': 'ValidUntill'
    }

    def __init__(self, user_id=None, support_key=None, valid_untill=None):  # noqa: E501
        """UserapiRefreshSupportkeyResponse - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._support_key = None
        self._valid_untill = None
        self.discriminator = None
        if user_id is not None:
            self.user_id = user_id
        if support_key is not None:
            self.support_key = support_key
        if valid_untill is not None:
            self.valid_untill = valid_untill

    @property
    def user_id(self):
        """Gets the user_id of this UserapiRefreshSupportkeyResponse.  # noqa: E501


        :return: The user_id of this UserapiRefreshSupportkeyResponse.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserapiRefreshSupportkeyResponse.


        :param user_id: The user_id of this UserapiRefreshSupportkeyResponse.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def support_key(self):
        """Gets the support_key of this UserapiRefreshSupportkeyResponse.  # noqa: E501


        :return: The support_key of this UserapiRefreshSupportkeyResponse.  # noqa: E501
        :rtype: str
        """
        return self._support_key

    @support_key.setter
    def support_key(self, support_key):
        """Sets the support_key of this UserapiRefreshSupportkeyResponse.


        :param support_key: The support_key of this UserapiRefreshSupportkeyResponse.  # noqa: E501
        :type: str
        """

        self._support_key = support_key

    @property
    def valid_untill(self):
        """Gets the valid_untill of this UserapiRefreshSupportkeyResponse.  # noqa: E501


        :return: The valid_untill of this UserapiRefreshSupportkeyResponse.  # noqa: E501
        :rtype: int
        """
        return self._valid_untill

    @valid_untill.setter
    def valid_untill(self, valid_untill):
        """Sets the valid_untill of this UserapiRefreshSupportkeyResponse.


        :param valid_untill: The valid_untill of this UserapiRefreshSupportkeyResponse.  # noqa: E501
        :type: int
        """

        self._valid_untill = valid_untill

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserapiRefreshSupportkeyResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserapiRefreshSupportkeyResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
