# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserapiSaveNotificationProfileRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'userid': 'str',
        'profile': 'object',
        'profiletype': 'int'
    }

    attribute_map = {
        'userid': 'userid',
        'profile': 'profile',
        'profiletype': 'profiletype'
    }

    def __init__(self, userid=None, profile=None, profiletype=None):  # noqa: E501
        """UserapiSaveNotificationProfileRequest - a model defined in Swagger"""  # noqa: E501
        self._userid = None
        self._profile = None
        self._profiletype = None
        self.discriminator = None
        self.userid = userid
        self.profile = profile
        self.profiletype = profiletype

    @property
    def userid(self):
        """Gets the userid of this UserapiSaveNotificationProfileRequest.  # noqa: E501

        The userid as obtained at the login  # noqa: E501

        :return: The userid of this UserapiSaveNotificationProfileRequest.  # noqa: E501
        :rtype: str
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """Sets the userid of this UserapiSaveNotificationProfileRequest.

        The userid as obtained at the login  # noqa: E501

        :param userid: The userid of this UserapiSaveNotificationProfileRequest.  # noqa: E501
        :type: str
        """
        if userid is None:
            raise ValueError("Invalid value for `userid`, must not be `None`")  # noqa: E501

        self._userid = userid

    @property
    def profile(self):
        """Gets the profile of this UserapiSaveNotificationProfileRequest.  # noqa: E501


        :return: The profile of this UserapiSaveNotificationProfileRequest.  # noqa: E501
        :rtype: object
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this UserapiSaveNotificationProfileRequest.


        :param profile: The profile of this UserapiSaveNotificationProfileRequest.  # noqa: E501
        :type: object
        """
        if profile is None:
            raise ValueError("Invalid value for `profile`, must not be `None`")  # noqa: E501

        self._profile = profile

    @property
    def profiletype(self):
        """Gets the profiletype of this UserapiSaveNotificationProfileRequest.  # noqa: E501


        :return: The profiletype of this UserapiSaveNotificationProfileRequest.  # noqa: E501
        :rtype: int
        """
        return self._profiletype

    @profiletype.setter
    def profiletype(self, profiletype):
        """Sets the profiletype of this UserapiSaveNotificationProfileRequest.


        :param profiletype: The profiletype of this UserapiSaveNotificationProfileRequest.  # noqa: E501
        :type: int
        """
        if profiletype is None:
            raise ValueError("Invalid value for `profiletype`, must not be `None`")  # noqa: E501

        self._profiletype = profiletype

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserapiSaveNotificationProfileRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserapiSaveNotificationProfileRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
