# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserapiAppLoginRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'secretkey': 'str',
        'interfacekey': 'str',
        'userspecs': 'object'
    }

    attribute_map = {
        'email': 'email',
        'secretkey': 'secretkey',
        'interfacekey': 'interfacekey',
        'userspecs': 'userspecs'
    }

    def __init__(self, email=None, secretkey=None, interfacekey=None, userspecs=None):  # noqa: E501
        """UserapiAppLoginRequest - a model defined in Swagger"""  # noqa: E501
        self._email = None
        self._secretkey = None
        self._interfacekey = None
        self._userspecs = None
        self.discriminator = None
        self.email = email
        self.secretkey = secretkey
        self.interfacekey = interfacekey
        self.userspecs = userspecs

    @property
    def email(self):
        """Gets the email of this UserapiAppLoginRequest.  # noqa: E501

        User its email adres, eg; test@test.com  # noqa: E501

        :return: The email of this UserapiAppLoginRequest.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserapiAppLoginRequest.

        User its email adres, eg; test@test.com  # noqa: E501

        :param email: The email of this UserapiAppLoginRequest.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def secretkey(self):
        """Gets the secretkey of this UserapiAppLoginRequest.  # noqa: E501

        secretkey as setup in the settings.env file  # noqa: E501

        :return: The secretkey of this UserapiAppLoginRequest.  # noqa: E501
        :rtype: str
        """
        return self._secretkey

    @secretkey.setter
    def secretkey(self, secretkey):
        """Sets the secretkey of this UserapiAppLoginRequest.

        secretkey as setup in the settings.env file  # noqa: E501

        :param secretkey: The secretkey of this UserapiAppLoginRequest.  # noqa: E501
        :type: str
        """
        if secretkey is None:
            raise ValueError("Invalid value for `secretkey`, must not be `None`")  # noqa: E501

        self._secretkey = secretkey

    @property
    def interfacekey(self):
        """Gets the interfacekey of this UserapiAppLoginRequest.  # noqa: E501

        The interfacekey as generated at login  # noqa: E501

        :return: The interfacekey of this UserapiAppLoginRequest.  # noqa: E501
        :rtype: str
        """
        return self._interfacekey

    @interfacekey.setter
    def interfacekey(self, interfacekey):
        """Sets the interfacekey of this UserapiAppLoginRequest.

        The interfacekey as generated at login  # noqa: E501

        :param interfacekey: The interfacekey of this UserapiAppLoginRequest.  # noqa: E501
        :type: str
        """
        if interfacekey is None:
            raise ValueError("Invalid value for `interfacekey`, must not be `None`")  # noqa: E501

        self._interfacekey = interfacekey

    @property
    def userspecs(self):
        """Gets the userspecs of this UserapiAppLoginRequest.  # noqa: E501

        Ignore, get filled by the webserver  # noqa: E501

        :return: The userspecs of this UserapiAppLoginRequest.  # noqa: E501
        :rtype: object
        """
        return self._userspecs

    @userspecs.setter
    def userspecs(self, userspecs):
        """Sets the userspecs of this UserapiAppLoginRequest.

        Ignore, get filled by the webserver  # noqa: E501

        :param userspecs: The userspecs of this UserapiAppLoginRequest.  # noqa: E501
        :type: object
        """
        if userspecs is None:
            raise ValueError("Invalid value for `userspecs`, must not be `None`")  # noqa: E501

        self._userspecs = userspecs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserapiAppLoginRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserapiAppLoginRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
