# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.botapi_add_bot_from_backtest_response import BotapiAddBotFromBacktestResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestBotapiAddBotFromBacktestResponse(unittest.TestCase):
    """BotapiAddBotFromBacktestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBotapiAddBotFromBacktestResponse(self):
        """Test BotapiAddBotFromBacktestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.botapi_add_bot_from_backtest_response.BotapiAddBotFromBacktestResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
