# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.haas_script_api_api import HaasScriptAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHaasScriptAPIApi(unittest.TestCase):
    """HaasScriptAPIApi unit test stubs"""

    def setUp(self):
        self.api = HaasScriptAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_script(self):
        """Test case for add_script

        """
        pass

    def test_backtest_script(self):
        """Test case for backtest_script

        Executes a backtest  # noqa: E501
        """
        pass

    def test_cancel_backtest(self):
        """Test case for cancel_backtest

        Cancels a running backtest  # noqa: E501
        """
        pass

    def test_create_new_backup(self):
        """Test case for create_new_backup

        Creates a backup of the given script  # noqa: E501
        """
        pass

    def test_debug_script(self):
        """Test case for debug_script

        Does a debug run of the script  # noqa: E501
        """
        pass

    def test_delete_script(self):
        """Test case for delete_script

        """
        pass

    def test_edit_script(self):
        """Test case for edit_script

        """
        pass

    def test_edit_script_sourcecode(self):
        """Test case for edit_script_sourcecode

        """
        pass

    def test_edit_script_specifications(self):
        """Test case for edit_script_specifications

        """
        pass

    def test_get_all_profiles(self):
        """Test case for get_all_profiles

        Returns the profiles per strategy  # noqa: E501
        """
        pass

    def test_get_all_script_items(self):
        """Test case for get_all_script_items

        """
        pass

    def test_get_all_script_records(self):
        """Test case for get_all_script_records

        """
        pass

    def test_get_backup(self):
        """Test case for get_backup

        Opens the backup file as new script  # noqa: E501
        """
        pass

    def test_get_backup_versions(self):
        """Test case for get_backup_versions

        Returns a list of the backup versions  # noqa: E501
        """
        pass

    def test_get_best_profiles(self):
        """Test case for get_best_profiles

        Returns the best profiles per market  # noqa: E501
        """
        pass

    def test_get_block(self):
        """Test case for get_block

        """
        pass

    def test_get_blocks(self):
        """Test case for get_blocks

        """
        pass

    def test_get_command(self):
        """Test case for get_command

        """
        pass

    def test_get_commands(self):
        """Test case for get_commands

        """
        pass

    def test_get_pattern_chart(self):
        """Test case for get_pattern_chart

        Returns the price pattern chart  # noqa: E501
        """
        pass

    def test_get_script_item(self):
        """Test case for get_script_item

        """
        pass

    def test_get_script_record(self):
        """Test case for get_script_record

        """
        pass

    def test_get_test_patterns(self):
        """Test case for get_test_patterns

        Returns all avilible test patterns  # noqa: E501
        """
        pass

    def test_init_script(self):
        """Test case for init_script

        Setup script and settings  # noqa: E501
        """
        pass

    def test_pattern_highscores(self):
        """Test case for pattern_highscores

        Returns the highet scores reached for a test pattern  # noqa: E501
        """
        pass

    def test_patterntest_script(self):
        """Test case for patterntest_script

        Executes a pattern test  # noqa: E501
        """
        pass

    def test_profile_script(self):
        """Test case for profile_script

        Renders a profile of the given strategy  # noqa: E501
        """
        pass

    def test_publish_community_script(self):
        """Test case for publish_community_script

        Publishes the strategy to haasscript.com (not used)  # noqa: E501
        """
        pass

    def test_publish_script(self):
        """Test case for publish_script

        Publishes the strategy to the webshop (not used)  # noqa: E501
        """
        pass

    def test_quick_run_script(self):
        """Test case for quick_run_script

        Does a brief backtest  # noqa: E501
        """
        pass

    def test_restore_backup(self):
        """Test case for restore_backup

        Restores a backup  # noqa: E501
        """
        pass

    def test_search_in_scripts(self):
        """Test case for search_in_scripts

        Tres to find code within the scripts  # noqa: E501
        """
        pass

    def test_unpublish_script(self):
        """Test case for unpublish_script

        Remove publication (not used)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
