# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.backtest_api_api import BacktestAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBacktestAPIApi(unittest.TestCase):
    """BacktestAPIApi unit test stubs"""

    def setUp(self):
        self.api = BacktestAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_backtest(self):
        """Test case for archive_backtest

        Controls to archive a backtest result or not  # noqa: E501
        """
        pass

    def test_delete_backtest(self):
        """Test case for delete_backtest

        Delete/remove a backtest result  # noqa: E501
        """
        pass

    def test_delete_unarchived_backtest(self):
        """Test case for delete_unarchived_backtest

        Deletes/removes all unarchived backtest results  # noqa: E501
        """
        pass

    def test_edit_backtest_tag(self):
        """Test case for edit_backtest_tag

        Changes a backtest tag  # noqa: E501
        """
        pass

    def test_get_backtest(self):
        """Test case for get_backtest

        Returns a stored backtest result  # noqa: E501
        """
        pass

    def test_get_backtest_runtime(self):
        """Test case for get_backtest_runtime

        Returns a stored backtest runtime  # noqa: E501
        """
        pass

    def test_get_full_backtest_history(self):
        """Test case for get_full_backtest_history

        Returns a list of all stored backtest results  # noqa: E501
        """
        pass

    def test_get_latest_backtests(self):
        """Test case for get_latest_backtests

        Returns a list of the latest stored backtest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
