# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.externalwalletapi_supported_currencies_request import ExternalwalletapiSupportedCurrenciesRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestExternalwalletapiSupportedCurrenciesRequest(unittest.TestCase):
    """ExternalwalletapiSupportedCurrenciesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalwalletapiSupportedCurrenciesRequest(self):
        """Test ExternalwalletapiSupportedCurrenciesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.externalwalletapi_supported_currencies_request.ExternalwalletapiSupportedCurrenciesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
