# coding: utf-8

"""
    Haasbot LocalAPI

    This is a rest api swagger for the Haasbot.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@haasonline.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.signalapi_edit_signal_request import SignalapiEditSignalRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestSignalapiEditSignalRequest(unittest.TestCase):
    """SignalapiEditSignalRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignalapiEditSignalRequest(self):
        """Test SignalapiEditSignalRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.signalapi_edit_signal_request.SignalapiEditSignalRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
