<BotSelectorScreen>:
    MainWindow:
        TitleLabel:
            text: "Select bot"

        ScrollView:
            id: scroll_view
            
        BoxLayout:
            size_hint_y: 0.1
            Button:
                text: 'Back to menu'
                on_release: root.manager.current = 'menu'
            Button:
                text: 'Confirm'
                on_release: root.confirm_selected_bots()
