from typing import Any

intervals: list[int] = [
    1,
    2,
    3,
    4,
    5,
    6,
    10,
    12,
    15,
    20,
    30,
    45,
    60,
    90,
    120,
    150,
    180,
    240,
    300,
    600,
    1200,
    2400,
]

columns: list[str] = [
    "roi",
    "trades",
    "interval",
    "signalconsensus",
    "fcc",
    "resetmiddle",
    "allowmidsells",
    "matype",
    "rsil",
    "rsib",
    "rsis",
    "bbl",
    "devup",
    "devdn",
    "macdfast",
    "macdslow",
    "macdsign",
]

cols = [
    "interval",
    "signalconsensus",
    "fcc",
    "resetmiddle",
    "allowmidsells",
    "matype",
    "rsil",
    "rsib",
    "rsis",
    "bbl",
    "devup",
    "devdn",
    "macdfast",
    "macdslow",
    "macdsign",
    "trades",
    "roi",
    "obj",
]


def get_bot_dict(bot: Any) -> dict[str, float or int or bool]:
    return {
        "roi": float(bot.roi),
        "interval": int(bot.interval),
        "signalconsensus": bool(bot.useTwoSignals),
        "fcc": bool(bot.bBands["RequireFcc"]),
        "resetmiddle": bool(bot.bBands["ResetMid"]),
        "allowmidsells": bool(bot.bBands["AllowMidSell"]),
        "matype": int(bot.bBands["MaType"]),
        "rsil": int(bot.rsi["RsiLength"]),
        "rsib": float(bot.rsi["RsiOversold"]),
        "rsis": float(bot.rsi["RsiOverbought"]),
        "bbl": int(bot.bBands["Length"]),
        "devup": float(bot.bBands["Devup"]),
        "devdn": float(bot.bBands["Devdn"]),
        "macdfast": int(bot.macd["MacdFast"]),
        "macdslow": int(bot.macd["MacdSlow"]),
        "macdsign": int(bot.macd["MacdSign"]),
        "trades": int(len(bot.completedOrders)),
        "obj": bot,
    }
